config/routes.rb
Rails.application.routes.draw do
  get 'schedules/create'
  get 'schedules/update'
  get 'schedules/edit'
  get 'schedules/new'
  get 'diaries/new', to: 'diaries#new', as: 'days'
  post 'diaries/new', to: 'diaries#create', as: 'days_create'
  get 'diaries/new/:id', to: 'diaries#show', as: 'days_new'
  get 'comments/new', to: 'comments#new', as: 'important_jobs'
  post 'comments/new', to: 'comments#create', as: 'important_jobs_create'
  get 'comments/:id', to: 'comments#show', as: 'important_jobs_show'
  root 'application#hello'
  resources :users
  resources :comments
  resources :schedules
  resources :diaries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/achieve_good.rb
class AchieveGood < ApplicationRecord
  belongs_to :day
end

app/models/achieve_todo.rb
class AchieveTodo < ApplicationRecord
  belongs_to :day
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :user
  has_one :achieve_good, dependent: :destroy
  has_one :achieve_todo, dependent: :destroy
  has_many :schedules, dependent: :destroy
  has_one :important_job, dependent: :destroy
  has_one :reflection_point, dependent: :destroy
end

app/models/important_job.rb
class ImportantJob < ApplicationRecord
  belongs_to :day
end

app/models/reflection_point.rb
class ReflectionPoint < ApplicationRecord
  belongs_to :day
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :day
end

app/models/user.rb
class User < ApplicationRecord
  has_many :days, dependent: :destroy
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello,world!"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @important_job = ImportantJob.new
    @achieve_todo = AchieveTodo.new
    @achieve_good = AchieveGood.new
    @reflection_point = ReflectionPoint.new
  end

  def update
  end

  def edit
    @improtant_job = ImportantJob.find(params[:id])
    @achieve_todo = AchieveTodo.find(params[:id])
    @achieve_good = AchieveGood.find(params[:id])
    @reflection_point = ReflectionPoint.find(params[:id])
  end

  def create
    @important_job = ImportantJob.new(important_params)
    @important_job.save!
    @achieve_todo = AchieveTodo.new(todo_params)
    @achieve_todo.save!
    @achieve_good = AchieveGood.new(good_params)
    @achieve_good.save!
    @reflection_point = ReflectionPoint.new(reflection_params)
    @reflection_point.save!
    redirect_to important_job_path(@important_job)
  rescue
    render action: 'new'
  end

  def show
    @important_job = ImportantJob.find(params[:id])
    @achieve_todo = AchieveTodo.find(params[:id])
    @achieve_good = AchieveGood.find(params[:id])
    @reflection_point = ReflectionPoint.find(params[:id])
  end

  private

    def important_params
      params.require(:important_job).permit(:content)
    end

    def todo_params
      params.require(:achieve_todo).permit(:content)
    end

    def good_params
      params.require(:achieve_good).permit(:content)
    end

    def reflection_params
      params.require(:reflection_point).permit(:content)
    end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  def index
    @day = Day.all
  end

  def new
    @day = Day.new
  end

  def create
    @day = Day.new(day_params)
    @day.user_id = 1
    if @day.save
      redirect_to @day
    else
    render 'new'
    end
  end

  def destroy
    Day.find(params[:id]).destroy
  end

  def show
    @day = Day.find(params[:id])
  end

  private

    def day_params
      params.require(:day).permit(:day)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def create
    @schedule = Schedule.new
    if @schedule.save
      redirect_to @schedule
    else
      render 'new'
    end
  end

  def update

  end

  def edit
  end

  def new
    @schedule = Schedule.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
    else
     render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
  end

  private

   def user_params
     params.require(:user).permit(:name, :email, :password,
                      :password_confirmation)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<%= provide(:title, "Edit Comments") %>
<h1>Comments</h1>

<%= form_for(@important_job) do |f| %>
  <%＝f.label :content %>
  <%= f.text_field :content %>
 <%= form.fields_for @achieve_todo do |g| %>
  <%= g.label :content %>
  <%= g.text_field :content %>
 <%= form.fields_for @achieve_good do |h| %>
  <%= h.label :content %>
  <%= h.text_field :content %>
 <%= form.fields_for @reflection_point do |i| %>
  <%= i.label :content %>
  <%= i.text_field :content %>
 <%= f.submit "Create new Comments" %>
<% end %>

app/views/comments/new.html.erb
<%= provide(:title, "Create Comments") %>
<h1>Create Comments</h1>

<%= form_for(@important_job) do |f| %>
  <%= f.label :ImportantJob %>
  <%= f.text_field :content %>
  <%= fields_for @achieve_todo do |achieve_todo| %>
    <%= achieve_todo.label :"Achieve To do" %>
    <%= achieve_todo.text_field :content %>
  <% end %>
  <%= fields_for @achieve_good do |achieve_good| %>
    <%= achieve_good.label :"Achieve Good" %>
    <%= achieve_good.text_field :content %>
  <% end %>
  <%= fields_for @reflection_point do |reflection_point| %>
    <%= reflection_point.label :"Reflection Point" %>
    <%= reflection_point.text_field :content %>
  <% end %>

  <%= f.submit "Create new Comments" %>
<% end %>

app/views/comments/show.html.erb
<p><%= @important_job.content %></p>
<p><%= @achieve_todo.content %></p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/diaries/_form.html.erb
<%= form_for(@day) do |f| %>
  <%= f.date_field :day %>
  <%= f.submit yield(:button_text) %>
<% end %>

app/views/diaries/create.html.erb
<h1>User Create!</h1>
<p>User Created!</p>
<p><%= link_to 'Show', diary %></p>

app/views/diaries/destroy.html.erb
<h1>Diaries#destroy</h1>
<p>Find me in app/views/diaries/destroy.html.erb</p>

app/views/diaries/index.html.erb
<h1>Day List</h1>

<table>
   <thead>
    <tr>
     <th>Day</th>
     <th colspan="3"></th>
    </tr>
   </thead>

<% @day.each do |day| %>
 <tr>
  <td><%= day.day %></td>
  <td><%= link_to 'Show', diary %></td>
 </tr>
<% end %>
</table>

<br>

<%= link_to 'New Day',new_diary_path %>

app/views/diaries/new.html.erb
<% provide(:title, 'diary task') %>
<% provide(:button_text, 'Create DailyTask') %>
<h1>Create DailyTask</h1>

  <%= render 'form' %>

app/views/diaries/show.html.erb
<h1>Diaries/h1>

<h2>Important Jobs</h2>
<p><%= important_job.content %></p>

<h2>Achieve Todos</h2>
<p><%= achieve_todos.content %></p>

<h2>Achieve Goods</h2>
<p><%= achieve_goods.content %></p>

<h2>Reflection Points</h2>
<p><%= reflection_point.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/create.html.erb
<h1>Schedules created</h1>
<p>Find me in app/views/schedules/create.html.erb</p>

app/views/schedules/edit.html.erb
<h1>Schedules#edit</h1>
<p>Find me in app/views/schedules/edit.html.erb</p>

app/views/schedules/new.html.erb
<%= provide(:title, 'New Schedule') %>

<h1>create schedule</h1>

<%= form_for(@schedule) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit "Create new Schedule" %>
<% end %>

app/views/schedules/update.html.erb
<h1>Schedules#update</h1>
<p>Find me in app/views/schedules/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>

 <%= f.label :email %>
 <%= f.email_field :email %>

 <%= f.label :password %>
 <%= f.password_field :password %>

 <%= f.label :password_confirmation %>
 <%= f.password_field :password_confirmation %>

 <%= f.submit yield(:button_text) %>
<% end %>

app/views/users/create.html.erb
<h1>User Create!</h1>
<p>User Created!</p>
<p><%= link_to 'Show', user %></p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>

  <%= render 'form' %>

app/views/users/index.html.erb
<h1>User List</h1>

<table>
 <thead>
  <tr>
   <th>Name</th>
   <th>Email</th>
   <th colspan="3"></th>
  </tr>
 </thead>

<% @users.each do |user| %>
 <tr>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= link_to 'Show', user %></td>
  <td><%= link_to 'Edit', edit_user_path(user) %></td>
  <td><%= link_to 'Destroy', user, method: :delete,
                    data:{confirm:'Are you sure?'}%></td>
 </tr>
<% end %>
</table>

<br>

<%= link_to 'New User',new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>

  <%= render 'form' %>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>